### ISSUE TITLE
Help to improve the docs button

### ISSUE THREAD

**Issue by odahcam** [nolimits4web/swiper-website#1]
Awesome to see swiper-website here!

Can I suggest to put something on docs like that? (taken from Vue.js docs)

![image](https://user-images.githubusercontent.com/3942006/35183327-595f1c28-fdcb-11e7-8464-888d04361508.png)

**Comment by DanielRuf** [comment]
Probably at https://github.com/nolimits4web/swiper-website/blob/master/src/jade/_internal-template.jade#L87-L97

**Comment by DanielRuf** [comment]
Or probably in the API docs.

**Comment by nolimits4web** [comment]
Done
