### ISSUE TITLE
Undocumented React Behaviour

### ISSUE THREAD

**Issue by tomjn** [nolimits4web/swiper-website#103]
Swiper v6 requires that the `<Swiper>` components immediate descendents are either `<SwiperSlide>` components, react fragments, or have a slot prop.

If a component does not meet these requirements, it is put outside the slider wrapper, **but this is not undocumented behaviour**.

### Expected Behavior

When visiting https://swiperjs.com/react the behaviour is documented

### Actual Behavior

When visiting https://swiperjs.com/react the behaviour is **not** documented

**Comment by vltansky** [comment]
Guess this can be closed now?

**Comment by tomjn** [comment]
I think it's changed but still holds true, and should be easier to document, perhaps something like this would do the trick:

> Markup that doesn't specify a slot, and isn't wrapped in a `<SwiperSlide>` will be assigned the end slot

What do you think?
