### ISSUE TITLE
Please add Angular 11 demos

### ISSUE THREAD

**Issue by ayoubkhan558** [nolimits4web/swiper-website#113]
Please add Angular 11 demos

**Comment by vltansky** [comment]
You have few demos in https://swiperjs.com/angular

https://stackblitz.com/edit/swiper-angular-example?file=src/app/app.component.ts
https://stackblitz.com/edit/swiper-angular-virtual?file=src%2Fapp%2Fapp.component.ts
https://stackblitz.com/edit/swiper-angular-fade?file=src/app/app.component.ts

Although demos is in Angular 10, but it shouldn't be some critical difference
