### ISSUE TITLE
Navigation, Pagination, Scrollbar boolean not accepted

### ISSUE THREAD

**Issue by Karmalakas** [nolimits4web/swiper-website#116]
Docs for all three say object or bool is accepted, but passing `true` has zero impact. Only if you specifically define selector or element, only then it starts working. So it's either the docs or plugin issue not getting defaults if `true` is passed.

I didn't check others, where mixed type is accepted, but I assume result would be the same.

**Comment by nolimits4web** [comment]
It will be enable the navigation module, but defaults for `nextEl`, `prevEl` (and similar) are `null`, so they must be implicitly specified. This case where it accepts `true` and just works is for React/Vue/Svelte/Angular components where it has default elements built-in

**Comment by Karmalakas** [comment]
That should be stated in the docs IMO. I've spent at least half an hour figuring out what I'm doing wrong :(
