### ISSUE TITLE
api examples use '<div className=' where just '<div class=' should be used

### ISSUE THREAD

**Issue by shmooth** [nolimits4web/swiper-website#127]
If you go here:
https://swiperjs.com/swiper-api#methods-and-properties

And scroll down to the 'Methods' section, you'll see examples of how to use addSlide() and appendSlide():

```
addSlide(1, '<div className="swiper-slide">Slide 10"</div>')

addSlide(1, [
 '<div className="swiper-slide">Slide 10"</div>',
 '<div className="swiper-slide">Slide 11"</div>'
]);
```

I changed those to just '**className=**' parts to just '**class=**', and things started working.

It's either a small oversight, or maybe because i'm using Vanilla JS (no other frameworks/Angular/Vue/etc).

I see a few other refs in the docs that mention 'className' in this way.

I would try to update the docs myself, but:
1. i'm not sure on this, and
2. i can't find the docs here.

**Comment by DAnn2012** [comment]
In fact the examples in the types source files contain **class** and not **className**...

**appendSlide**:

https://github.com/nolimits4web/swiper/blob/c459686f6baa91409c11a1115ba53f95d2ceff9e/src/types/swiper-class.d.ts#L294-L309

**prependSlide**:

https://github.com/nolimits4web/swiper/blob/c459686f6baa91409c11a1115ba53f95d2ceff9e/src/types/swiper-class.d.ts#L311-L325

**addSlide**:

https://github.com/nolimits4web/swiper/blob/c459686f6baa91409c11a1115ba53f95d2ceff9e/src/types/swiper-class.d.ts#L327-L340

**Comment by shmooth** [comment]
I'm guessing the use of 'className' instead of 'class' is due, at least in part, to the fact that 'className' is the required syntax when using React/JSX.

**Comment by DAnn2012** [comment]
You're absolutely right, but it would be worth specifying that the examples are for the required syntax when using React/JSX.

In my opinion, you were right to report it to the author.
