### ISSUE TITLE
.disableKeyboardControl() and .enableKeyboardControl() method docs are outdated

### ISSUE THREAD

**Issue by applecat** [nolimits4web/swiper-website#13]
Seems like mySwiper.disableKeyboardControl() and mySwiper.enableKeyboardControl() are not used any more: http://idangero.us/swiper/api/#methods
In swiper now there are swiper.keyboard.enable() and swiper.keyboard.disabled() methods available.

**Comment by nolimits4web** [comment]
Fixed, thanks
