### ISSUE TITLE
The type for control parameter of the .d.ts file is not reported correctly in the documentation

### ISSUE THREAD

**Issue by DAnn2012** [nolimits4web/swiper-website#157]
One of the types for `control` parameter ( **Swiper[]** ) currently present in the .d.ts files is not reported correctly in the documentation and is therefore omitted:

![control](https://user-images.githubusercontent.com/1197819/124380302-44bafe80-dcbc-11eb-8851-e7fa04c1d29f.png)

https://github.com/nolimits4web/swiper/blob/8d1249c699428fd49ec2e6cc7b6ed45150a11ac8/src/types/components/controller.d.ts#L14-L18

![control-2](https://user-images.githubusercontent.com/1197819/124380337-6ddb8f00-dcbc-11eb-9d8e-14335b080fce.png)

@nolimits4web I remind you that even the type for **bullets** and **slides** of the .d.ts file is not reported correctly in the documentation https://github.com/nolimits4web/swiper/issues/4694

Thanks.

**Comment by nolimits4web** [comment]
Fixed
