### ISSUE TITLE
[QUESTION]: React load slides dynamically async

### ISSUE THREAD

**Issue by simplecommerce** [nolimits4web/swiper-website#159]
Hi,

I am trying to find an example on how to load slides dynamically after fetching them from a query from my datasource.

I was thinking I would have to use virtual slides.

But your example seems to be automated and doesn't allow me to use `renderExternal` to fetch the data?

This is the example I am looking at: https://swiperjs.com/react#virtual-slides

What I want is to load by default X amount of slides, but when they click `next`, if they reach near the end, it will fetch the remote to see if there is additional data and update the slides.

I might be missing something or not understanding it correctly.

Hope you can point me out in the right direction.

Thanks!

**Comment by nolimits4web** [comment]
Website issue is not the appropriate place for asking questions and get support. Please use Swiper's discussions for this https://github.com/nolimits4web/swiper/discussions
