### ISSUE TITLE
Links on demo page arent working

### ISSUE THREAD

**Issue by joxy379** [nolimits4web/swiper-website#160]
I can't click the demo links for the different frameworks:

![image](https://user-images.githubusercontent.com/36665384/124558736-36dfb780-de3b-11eb-9338-df63ef59c9ef.png)

The links lead to nowhere. Maybe a little mistake?

Thansk in advance!

**Comment by nolimits4web** [comment]
Everything works there. Probably you have some network issues, or you disallowed to open new windows from the website.
