### ISSUE TITLE
Documentation for version 6

### ISSUE THREAD

**Issue by vk2r** [nolimits4web/swiper-website#177]
At the moment I am working on CRA and I have not found the way to configure the ESM modules, so I have decided to use version 6. The problem is that I can find the documentation for the previous version.

I would like to know if this documentation exists and where I can find it.

Thank you.

**Comment by vk2r** [comment]
Sorry. I have the wrong Git.
A thousand apologies.

**Comment by marquizzo** [comment]
I'm on the same boat. I've recently joined a project that's using `v6.6.1` and it would be very helpful if the API docs for 6.x were still available online somewhere!

This is the best I could find by scouring through old branches of their website's repo: https://github.com/nolimits4web/swiper-website/blob/v6/src/pages/get-started.mdx

**Comment by DAnn2012** [comment]
Something is also available on archive.org, for example these pages for `v6.8.4`:

- https://web.archive.org/web/20210825022443/https://swiperjs.com/get-started
- https://web.archive.org/web/20210825021924/https://swiperjs.com/swiper-api

**Comment by songoo** [comment]
Sorry for duplicit topic, hi folks, on same boat :) cant install 7 since of some node issues, so got working 6, but its a bit guess work. Old doc would be super helpfull :P

**Comment by vltansky** [comment]
https://swiper6.vercel.app/

**Comment by jonlemmon** [comment]
@nolimits4web can you please put a link to older documentation on the Swiper 7 website? It took me 20 minutes to find this thread...

Every other module on the planet links to their old documentation from their current documentation website.

**Comment by qiutian00** [comment]
> https://swiper6.vercel.app/

tanks a lot.
