### ISSUE TITLE
Domain "swiperjs.com" expired. (not renewed)

### ISSUE THREAD

**Issue by guedesleandro** [nolimits4web/swiper-website#184]
Hello,

Your domain "swiperjs.com" was expired today 09/16. And the website is down redirecting to "namecheap.com". I think you have forgotten to renew it. ;)

**Comment by DAnn2012** [comment]
Now the website is up. The domain has been renewed for another year.

**Comment by vltansky** [comment]
@guedesleandro thanks for reporting!
