### ISSUE TITLE
No version 6 documentation available anymore

### ISSUE THREAD

**Issue by lspoor** [nolimits4web/swiper-website#188]
Is there a reason previous version documentation is not available? I'm sticking with v6 for now and there is no longer any docs available.

**Comment by e-bogatko** [comment]
I have the same problem 
Project which I work have problem with new version swiper
What do I need do to find docs for v6?
If somebody have docs on swiper v6, please, send me

**Comment by lspoor** [comment]
Hi, they can be viewed here - https://swiper6.vercel.app/swiper-api
