### ISSUE TITLE
Documentation for Virtual Slides

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [nolimits4web/swiper-website#19]
Virtual Slides seems like it would be a great feature for mobile. However there's no documentation for for the different configs like renderExternal... could you add this to the example in the form of an Angular app?

**Comment by leomercier** [comment]
Very hacky but works. Through rendering components as html.

Would be great to have documentation on it and do properly.

```
sliderRender(){
    return this.props.pins.map((data, key) => {
      // need for virtualised rendering
      return ReactDOMServer.renderToStaticMarkup(<MapItem
          key={key}
          data={data}
        />);
    })
  }
  render() {
    var params = {
      spaceBetween: 0,
      slidesPerView: 1,
      virtual: {
        slides: (this.sliderRender)()
      },
      observer: true,
      observeParents: true,
    };
    return (
      <div className={classNames("map-item__container", { open: this.props.showMapItem })}>
        <Swiper {...params} ref={node => { if(node) return this.swiper = node.swiper } } />
      </div>
    )
  }
```

I've seen this https://stackoverflow.com/questions/47467943/swiper-renderexternal-example-in-virtual-slides-with-react but couldn't get it to work.

**Comment by nolimits4web** [comment]
Added React and Vue examples of `renderExternal` usage

**Comment by hacknug** [comment]
@nolimits4web is it possible to use it without React or Vue?

**Comment by snimavat** [comment]
@nolimits4web 

There are examples here : https://swiperjs.com/demos#virtual-slides
But I dont find any example that shows how `renderExterna`l can be implemented especially when using a component framework

There are examples of vue/react , but there's no example of core or element, that uses a`renderExternal` and rendering is done by vue or react etc
