### ISSUE TITLE
Module not found:  Can't resolve 'swiper/css'

### ISSUE THREAD

**Issue by luckydevboy** [nolimits4web/swiper-website#192]
According to the solution, [m-keshavarz](https://stackoverflow.com/users/17022686/m-keshavarz) said in [Stackoverflow](https://stackoverflow.com/questions/69154197/module-not-found-cant-resolve-swiper-css) `import 'swiper/css';` in [this section](https://swiperjs.com/react#usage) should be replaced by:
```
import 'swiper/swiper-bundle.min.css'
import 'swiper/swiper.min.css'
```

**Comment by 01faiz** [comment]
still not run

**Comment by maharabhossain1** [comment]
Is there any solution for the **Gatsby** project? 
cause I tried this 
import 'swiper/swiper-bundle.min.css'
import 'swiper/swiper.min.css'

but in **production**, it's **not working**.

**Comment by olegtremba1234** [comment]
I'm imported to file index.css like this:
`@import 'swiper/css';
@import "swiper/css/pagination";`

Vite+React+TS

**Comment by ryanfavour4** [comment]
Does anyone have a real solution yet?

`import "swiper/swiper-bundle.css";`

This seems to work, but I bet this won't work in prod. This is Vite React v6, Swiper v11
