### ISSUE TITLE
[Documentation] Typo on Documentation

### ISSUE THREAD

**Issue by permanar** [nolimits4web/swiper-website#193]
https://swiperjs.com/swiper-api#parameters

![Screenshot_87](https://user-images.githubusercontent.com/25473432/141132564-827c6e39-d8d7-4648-ad19-f78fce29348c.jpg)

Hi, when I play around the documentation, I found this small typo (probably).

Did you probably mean it as '_properly_' instead of '_property_' by any chance?

**Comment by vltansky** [comment]
Thanks for reporting! fixed in https://github.com/nolimits4web/swiper/pull/5187
