### ISSUE TITLE
Swiper React virtual slides don't work with slidesPerView={"auto"}

### ISSUE THREAD

**Issue by CitizenBeta** [nolimits4web/swiper-website#195]
https://codesandbox.io/s/swiper-virtual-slides-react-forked-lquzk?file=/src/App.jsx

If you change the slidesPerView={"auto"} to slidesPerView={3} it'll work again.

Stack trace:

> Unhandled Runtime Error
> TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
> 
> Call Stack
> Swiper.updateSlides
> node_modules/swiper/core/update/updateSlides.js (112:0)
> Swiper.update
> node_modules/swiper/core/core.js (345:0)
> updateSwiper
> node_modules/swiper/react/update-swiper.js (128:0)
> eval
> node_modules/swiper/react/swiper.js (145:18)
> commitHookEffectListMount
> node_modules/react-dom/cjs/react-dom.development.js (20573:0)
> commitLifeCycles
> node_modules/react-dom/cjs/react-dom.development.js (20634:0)
> commitLayoutEffects
> node_modules/react-dom/cjs/react-dom.development.js (23426:0)
> HTMLUnknownElement.callCallback
> node_modules/react-dom/cjs/react-dom.development.js (3945:0)
> Object.invokeGuardedCallbackDev
> node_modules/react-dom/cjs/react-dom.development.js (3994:0)
> invokeGuardedCallback
> node_modules/react-dom/cjs/react-dom.development.js (4056:0)
> commitRootImpl
> node_modules/react-dom/cjs/react-dom.development.js (23151:0)
> unstable_runWithPriority
> node_modules/scheduler/cjs/scheduler.development.js (468:0)
> runWithPriority$1
> node_modules/react-dom/cjs/react-dom.development.js (11276:0)
> commitRoot
> node_modules/react-dom/cjs/react-dom.development.js (22990:0)
> performSyncWorkOnRoot
> node_modules/react-dom/cjs/react-dom.development.js (22329:0)
> eval
> node_modules/react-dom/cjs/react-dom.development.js (11327:0)
> unstable_runWithPriority
> node_modules/scheduler/cjs/scheduler.development.js (468:0)
> runWithPriority$1
> node_modules/react-dom/cjs/react-dom.development.js (11276:0)
> flushSyncCallbackQueueImpl
> node_modules/react-dom/cjs/react-dom.development.js (11322:0)
> flushSyncCallbackQueue
> node_modules/react-dom/cjs/react-dom.development.js (11309:0)
> flushSync
> node_modules/react-dom/cjs/react-dom.development.js (22467:0)
> Object.scheduleRefresh
> node_modules/react-dom/cjs/react-dom.development.js (24429:0)
> eval
> node_modules/react-refresh/cjs/react-refresh-runtime.development.js (304:0)
> Set.forEach
> <anonymous>
> Object.performReactRefresh
> node_modules/react-refresh/cjs/react-refresh-runtime.development.js (293:0)
> eval
> node_modules/@next/react-refresh-utils/internal/helpers.js (125:0)

**Comment by nolimits4web** [comment]
Virtual sides doesn't support slidesPerView auto
