### ISSUE TITLE
API Docs for v6 are missing

### ISSUE THREAD

**Issue by vaxul** [nolimits4web/swiper-website#199]
In previous version (like v5) and [API.md](https://github.com/nolimits4web/swiper/blob/Swiper5/API.md) were provided.

I can't find any documentation for the v6. Neither on the website nor on Github.

Please provide a valid API-documentation for v6 and link it within the readme.

**Comment by nolimits4web** [comment]
How about doing issues search before posting a new one? https://github.com/nolimits4web/swiper-website/issues/177
