### ISSUE TITLE
demos does not have link 

### ISSUE THREAD

**Issue by vczb** [nolimits4web/swiper-website#200]
I looked for the example [grid](https://swiperjs.com/demos#slides-grid) and there was no link anywhere

I noticed that several other examples are unlinked as well.

**Comment by vltansky** [comment]
Which link is missed?
Core, React and other examples are onClick functions, not links.

**Comment by vczb** [comment]
> 

OMG you are right!

**Comment by vczb** [comment]
@vltansky i will close this issue, thanks for quickly answer
