### ISSUE TITLE
There are errors in docs

### ISSUE THREAD

**Issue by stratboy** [nolimits4web/swiper-website#207]
Hi, I think there are errors in docs, at leat on following pages:

https://swiperjs.com/migration-guide
https://swiperjs.com/get-started

there are definitley conflicting instructions about how to import js and css modules and about how to configure modules. Your docs are not coherent between different pages and about different swiper versions.

For css module, currently cannot be imported like this:

import 'swiper/components/navigation/navigation.min.css'

nor like this:

import 'swiper/css/navigation'

on current version of swiper, they are under swiper/modules/modulename

for js modules, there are other issues on docs, please check them out.

**Comment by nolimits4web** [comment]
If it doesn't work for you

```
import 'swiper/css/navigation'
```
then your env doesn't support pure ES modules

**Comment by stratboy** [comment]
> If it doesn't work for you
> 
> ```
> import 'swiper/css/navigation'
> ```
> 
> then your env doesn't support pure ES modules

They're css, not js. I'm currently on Dark Sass. Also, on current version of swiper, they are under swiper/modules/modulename, css folder doesn't exist.
