### ISSUE TITLE
Error in 1.7.1

### ISSUE THREAD

**Issue by GimpMaster** [nolimits4web/swiper-website#23]
It seems that the allowTouchMove is not the correct variable anymore. This variable has changed to onlyExternal, from my understanding. Can you update the docs?

**Comment by nolimits4web** [comment]
What is 1.7.1? Everything is correct in docs

**Comment by GimpMaster** [comment]
Sorry. I mean the last version of Framework 7. The swiper code does not have a variable called allowTouchMove. When looking through the code this is all I could find.....

https://github.com/framework7io/framework7/blob/v1/src/js/swiper/swiper.js#L105

Which seems to be what allowTouchMove is supposed to be.

**Comment by nolimits4web** [comment]
1.7.1 uses old Swiper 3.x, docs is for latest Swiper 4.c

**Comment by GimpMaster** [comment]
Real quick....is there a way to see the old Swiper 3.x docs online with out me having to pull the repo and download.....or are the docs in Framework v1 somewhere?

**Comment by GimpMaster** [comment]
Thanks Vlad
