### ISSUE TITLE
swiper.esm.js doesn't export only Swiper

### ISSUE THREAD

**Issue by stratboy** [nolimits4web/swiper-website#236]
I just realised that swiper.esm.js exports pretty everything, not only Swiper. So docs are wrong, I guess. They state:

By default Swiper exports only core version without additional modules (like Navigation, Pagination, etc.)

https://swiperjs.com/get-started

Instead:

```js
export { default as Swiper, default } from './core/core.js';
export { default as Virtual } from './modules/virtual/virtual.js';
export { default as Keyboard } from './modules/keyboard/keyboard.js';
export { default as Mousewheel } from './modules/mousewheel/mousewheel.js';
export { default as Navigation } from './modules/navigation/navigation.js';
export { default as Pagination } from './modules/pagination/pagination.js';
export { default as Scrollbar } from './modules/scrollbar/scrollbar.js';
export { default as Parallax } from './modules/parallax/parallax.js';
export { default as Zoom } from './modules/zoom/zoom.js';
export { default as Lazy } from './modules/lazy/lazy.js';
export { default as Controller } from './modules/controller/controller.js';
export { default as A11y } from './modules/a11y/a11y.js';
export { default as History } from './modules/history/history.js';
export { default as HashNavigation } from './modules/hash-navigation/hash-navigation.js';
export { default as Autoplay } from './modules/autoplay/autoplay.js';
export { default as Thumbs } from './modules/thumbs/thumbs.js';
export { default as FreeMode } from './modules/free-mode/free-mode.js';
export { default as Grid } from './modules/grid/grid.js';
export { default as Manipulation } from './modules/manipulation/manipulation.js';
export { default as EffectFade } from './modules/effect-fade/effect-fade.js';
export { default as EffectCube } from './modules/effect-cube/effect-cube.js';
export { default as EffectFlip } from './modules/effect-flip/effect-flip.js';
export { default as EffectCoverflow } from './modules/effect-coverflow/effect-coverflow.js';
export { default as EffectCreative } from './modules/effect-creative/effect-creative.js';
export { default as EffectCards } from './modules/effect-cards/effect-cards.js';
```

I think this is the reason webpack does bundle everything even if I only import Swiper and Navigation/Pagination exactly like written in docs.

**Comment by nolimits4web** [comment]
Sorry, but it is a question to webpack/config why tree shaking doesn't work there for you. Everything is correct in Swiper.

**Comment by stratboy** [comment]
Hi, thank you. But what do you mean then, with 

_By default Swiper exports only core version without additional modules_

The code above is straight from swiper.esm.js

I'm not super in es-modules, I just want to understand why that file is said to only export core while it seems to export quite about anything.

**Comment by nolimits4web** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export#description

> There are two different types of export, named and default

`By default Swiper exports only core version without additional modules` - means what is exported with `default export` from package, e.g. `export default ...`

**Comment by stratboy** [comment]
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export#description
> 
> > There are two different types of export, named and default
> 
> `By default Swiper exports only core version without additional modules` - means what is exported with `default export` from package, e.g. `export default ...`

Ok thank you. So as you stated, if I correctly undestand, the issue is that webpack should cut away all the non-imported modules that are exported in swiper.esm.js, due to tree shaking, right?

Excuse me for the many questions.. :)

**Comment by nolimits4web** [comment]
Yes, the proper bundler should remove from bundle not used modules

**Comment by stratboy** [comment]
Ok found out the thing: had for some reason to apply sideEffects:false at loader level instead of package level:

```js
  module: {
    rules: [
      {
        test: /swiper\.esm\.js/,
        sideEffects: false
      }
    ]
  }
```
  
  This setting will let webpack to tree shake swiper.
