### ISSUE TITLE
todo: enable https

### ISSUE THREAD

**Issue by DanielRuf** [nolimits4web/swiper-website#24]
Currently URLs like https://www.idangero.us/swiper/dist/css/swiper.min.css redirect to the http version.

**Comment by nolimits4web** [comment]
Don't use `www`

**Comment by DanielRuf** [comment]
Well, it was like this ;-) It seems it is fixed now. The certificate was not properly configured.

**Comment by DanielRuf** [comment]
Also these URLs are referenced in the docs / website.
