### ISSUE TITLE
package no longer ships with `css/` 

### ISSUE THREAD

**Issue by LucasZapico** [nolimits4web/swiper-website#249]
I am addressing this issue as a documentation issue, though it may be part of something more. The docs call out importing the styles from  'swiper/css' or `~swiper/css/<module-name>`. This directory does not appear to exist in the package anymore. I have dug around a bit and haven't been able to resolve the styles. 

__Expected Experience__

1. If the package is altered the documentation is updated or versioned. 

Please let me know what I am missing. 

Thank you.

**Comment by nolimits4web** [comment]
You need to learn what is pure ES modules and how package.json `exports` fields works
