### ISSUE TITLE
Some Pagination and Virtual Slides parameters have no default value and description

### ISSUE THREAD

**Issue by DAnn2012** [nolimits4web/swiper-website#255]
Some Pagination and Virtual Slides parameters have no default value (null) and description. They are the ones that have a function as a type.

**Pagination**:
![pagination](https://user-images.githubusercontent.com/1197819/166142944-732221a2-448b-4adb-b027-c757665c6534.png)

![pagination2](https://user-images.githubusercontent.com/1197819/166142949-04413c1a-5678-4d52-9c84-b75b52fcef6f.png)

**Virtual Slides**:
![virtual-slides](https://user-images.githubusercontent.com/1197819/166142951-20dc2ba8-e68e-4928-adcc-3122974ef6a2.png)

Thanks.

**Comment by DAnn2012** [comment]
Hello @nolimits4web 

as soon as you can, could you take a look at this problem?

Thanks.

**Comment by DAnn2012** [comment]
Hello @nolimits4web 

the problem is still present even after the update following the release of version 8.3.2.

as soon as you can, could you take a look at this problem?

Thanks.

**Comment by DAnn2012** [comment]
Hello @vltansky 

I remember you also solved problem #169 

Please, Is it possible to take a look at this here as well?

Thank you.

**Comment by vltansky** [comment]
Hey, @DAnn2012 I'm on vacation right now, I will take a look in a week.
Ping me again if needed

**Comment by DAnn2012** [comment]
Hello @vltansky 

I'm sorry to bother you.

Please, have you already taken a look at the problem?

Thank you.
