### ISSUE TITLE
Angular Swiper Reference Unit testing

### ISSUE THREAD

**Issue by rickvandermey** [nolimits4web/swiper-website#262]
When using the reference in Angular with `@ViewChild()` I would like some docs or some guidance in how to setup my unit test.
This because the SwiperComponent is not defined.

When I try `fixture.detectChanges()` SwiperComponent defaults seems to be empty and therefor cannot be set in the TestBed Configuration.
Also tried to with `app.swiper = TestBed.inject(SwiperComponent)` inside the Unit test, but then i need to provide SwiperComponent and after that ElementRef (which cant be provided)

This is the code I'm currently using
https://swiperjs.com/angular#accessing-swiper-reference

**Comment by nolimits4web** [comment]
There is no Angular version anymore
