### ISSUE TITLE
Demo for slidesPerColumn broken?

### ISSUE THREAD

**Issue by vaxul** [nolimits4web/swiper-website#269]
I would expect, that the demo for [Slides per column](https://swiperjs.com/demos#slides-per-column) would show some multirow layout like:
![image](https://user-images.githubusercontent.com/3798226/191464971-c6b55a36-9ed4-4e3a-b594-2fffc6733213.png)

Instead it looks broken:
![image](https://user-images.githubusercontent.com/3798226/191465318-b23262e7-d0bc-4695-876e-35ef0fdabebe.png)

Tested in latest Chrome and Firefox.

[Link to the Demo CodeSandbox](https://codesandbox.io/s/x3r56n?file=/index.html)

This is also true for the [Swiper 6 Demo](https://swiper6.vercel.app/demos#slides-per-column) (which I have to work with).

**Comment by nolimits4web** [comment]
This is a bug with demo, use `Grid` demo https://swiperjs.com/demos#grid
