### ISSUE TITLE
in docs/demos links to codesandbox are broken/wrong

### ISSUE THREAD

**Issue by McFoggy** [nolimits4web/swiper-website#272]
On the demos page of the documentation, clicking on any link to code samples 

![image](https://user-images.githubusercontent.com/1119660/200113623-b6860953-0899-4107-80e4-03b8b98e46f2.png)

bring to a codesandbox page (https://codesandbox.io/api/v1/sandboxes/define) showing the following error:

```
{"error":"This endpoint requires the params `files` or `parameters` in order to work. See https://codesandbox.io/docs/importing#create-wizard for more details."}
```

**Comment by nolimits4web** [comment]
all works, at least at the moment
