### ISSUE TITLE
Missing documentation: Inject custom css styles in Angular using Swiper Element

### ISSUE THREAD

**Issue by fellmann** [nolimits4web/swiper-website#298]
https://swiperjs.com/element#injecting-styles

Documentation states that `swiperEl.initialize()` should be called manually after setting injectStyles.

This is probably not correct, a the swiper is initialized automatically and setting styles afterwards does not work.

**Comment by nolimits4web** [comment]
Read docs carefully `init="false"` must be set on swiper-container
