### ISSUE TITLE
use docusaurus

### ISSUE THREAD

**Issue by zebapy** [nolimits4web/swiper-website#3]
Would be great to use http://docusaurus.io/ for docs so content can be in markdown. Also these docs should be with the plugin sourcecode so it's easy for people to find without having to use the website. Secondly, there's no docs for v3 that I can tell in this repo.

**Comment by nolimits4web** [comment]
Sorry, but there is no way for me to rewrite everything from scratch. v3 docs source is probably lost. This is what left https://github.com/nolimits4web/swiper/blob/Swiper3/API.md
