### ISSUE TITLE
Demo links are broken on the website.

### ISSUE THREAD

**Issue by jonnyjones99** [nolimits4web/swiper-website#326]
Seems like the demos don't link though to anything. The 'open in new window' button works, but clicking on 'core', 'react' etc, to see the source code doesn't link through to anything.

![Screenshot 2023-05-25 at 10 04 21](https://github.com/nolimits4web/swiper-website/assets/72031997/a0ffe2c7-571b-43d5-a139-f5897358c405)

Page: https://swiperjs.com/demos

**Comment by nolimits4web** [comment]
As I see everything works
