### ISSUE TITLE
CDN lastest version update

### ISSUE THREAD

**Issue by muhammedkaraoglu** [nolimits4web/swiper-website#406]
First of all, thank you for the v11.1.7 Bugfix. @nolimits4web 
When I woke up in the morning, I was really worried that none of the sliders were working.  But there is still one CDN that is not fixed. 

https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js brings v11.1.6.

**Comment by nolimits4web** [comment]
Update cache or wait for cdn to update it
