### ISSUE TITLE
Error on page https://swiperjs.com/api/#parameters

### ISSUE THREAD

**Issue by Almages** [nolimits4web/swiper-website#44]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.1

Error on page https://swiperjs.com/api/#parameters on comment in breakpoints parameters sample : it is <= and not >=

**Comment by nolimits4web** [comment]
This docs API is for v5, all correct there
