### ISSUE TITLE
Wrong url for CDN on Stackblitz

### ISSUE THREAD

**Issue by italosimpli** [nolimits4web/swiper-website#58]
This is more a heads up than an issue. When trying to edit the demo on Stackblitz, JS and CSS are not loaded because the version is not specified and version 6 is using a different folder structure, so the user needs to specify the version (i.e. `https://unpkg.com/swiper@5/css/swiper.min.css` similar for `js` file) or make sure to change the url (`https://unpkg.com/swiper/swiper-bundle.min.css` similar for `js` file).

This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.
* Platform/Target and Browser Versions: Any.
* Live Link or JSFiddle/Codepen or website with issue: https://stackblitz.com/edit/swiper-demo-1-default?&file=index.html

### What you did
Try to edit demo in Stackblitz.

### Expected Behavior
Swiper working properly with CSS implemented.

### Actual Behavior
CSS and JS not loaded when using it from CDN.

>PS: If this should not be open as an issue, I apologize and would be happy to be informed how to proceed in similar situations.

**Comment by italosimpli** [comment]
Hi @lastnoob . 

English is not my first language so I am not sure if I was clear above.
The actual problem is that the new version (**v6**) do not follow the same file structure and naming as **v5** and earlier.

It is true that most websites using the CDN might be broken, but only **IF** they are not specifying the version on the url path.

When you use the CDN `https://unpkg.com/swiper/` you are requesting the most recent version, but you can specify the version adding `@[version number]` to the directory name, like: `https://unpkg.com/swiper@5/`.

The problem here is if you request the version 5, the `CSS` and `JS` files are located inside their respective folder, so you will find them in (assuming you are using the minified files):

- `/js/swiper.min.js` and
- `/css/swiper.min.css`

So the final url would be something like:

- `https://unpkg.com/swiper@5/js/swiper.min.js` and
- `https://unpkg.com/swiper@5/css/swiper.min.css`

**But** if you are willing to use the newest version you can refer to the documentation (that is up to date with the changes):

```html
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.css">
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">

<script src="https://unpkg.com/swiper/swiper-bundle.js"></script>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
```

Notice that the files are now located on the `root` folder (there is no `/js/` ro `/css/`) and the name changed from `swiper` to `swiper-bundle`.

I would recommend to always specify the version when you use CDN to avoid unexpected behaviours when a new version is released.

**Comment by isdiop** [comment]
Same problem, but i fixed with the new url that you can found 
here :  https://swiperjs.com/get-started/

```
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.css">
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">

<script src="https://unpkg.com/swiper/swiper-bundle.js"></script>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
```

**Comment by Daniel-Bertagnolli** [comment]
Was going to open an issue with this same problem but i see it's already here so i'm just adding my comment here. For me this is a minor issue since i've been using this swiper for like 4 years now (and still have to check the docs sometimes) but for someone who's approaching for the first time it could be a bit of an issue when they try the code on stackblitz and it doesn't work

**Comment by vltansky** [comment]
Should be closed. Stackblitz demos are up to date
